[tools]
# core language runtimes
node = "lts"
bun = "latest"
python = "3.13"
rust = "latest"

# CLI tools
uv = "latest"
starship = "latest"
gh = "latest"
bat = "latest"
fd = "latest"
jq = "latest"
ripgrep = "latest"
eza = "latest"
opencode = "latest"
yq = "latest"
claude = "latest"
codex = "latest"
pi = "latest"

# lint & format
shellcheck = "latest"
shfmt = "latest"
actionlint = "latest"
markdownlint-cli2 = "latest"
pre-commit = "latest"
neovim = "latest"
"github:can1357/oh-my-pi" = "latest"
herdr = "latest"
lazygit = "latest"
hunk = "latest"

[settings]
github_attestations = false

[settings.npm]
package_manager = "bun"
