[tools]
# core language runtimes
node = "lts"
bun = "latest"
python = "3.13"
rust = "latest"

# CLI tools
uv = "latest"
starship = "latest"
gh = "latest"
bitwarden = "latest"
bat = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
ripgrep = "latest"
zoxide = "latest"
eza = "latest"
delta = "latest"
dust = "latest"
zellij = "latest"
neovim = "latest"
opencode = "latest"
btop = "latest"
gcloud = "latest"
yq = "latest"
yazi = "latest"
lazygit = "latest"
claude = "latest"
codex = "latest"

[settings]

[settings.npm]
package_manager = "bun"
